name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
    
    steps:
    - uses: actions/checkout@v1

    - name: Change PHP version
      run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }} && php -v

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test server
      run: composer test-server

    - name: Run test suite
      run: composer test
